all:
	javac -d ./bin -classpath ./bin ./src/MathService.java
	javac -d ./bin -classpath ./bin ./src/MathServiceImpl.java
	javac -d ./bin -classpath ./bin ./src/server.java
	javac -d ./bin -classpath ./bin ./src/client.java

#rmic -d ./bin -classpath ./bin MathServiceImpl
#start rmiregistry 6789
